# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r
sudo: false
cache: packages
warnings_are_errors: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#matrix: 3x Linux, 1x OS X
matrix:
  include:
  - r: release
  - r: devel

#notifications
notifications:
  email:
    on_success: change
    on_failure: change


#after_success
after_success:
- Rscript -e 'covr::codecov()'

# Custom parts:

#r_github_packages
r_github_packages:
- jimhester/covr





