# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r
warnings_are_errors: true
sudo: required

r_github_packages:
  - jimhester/covr
  - r-lib/testthat
  
#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

notifications:
  email:
    on_success: change
    on_failure: change
    
include:
- r: release
- r: oldrel

before_install:
- mkdir -p ~/.R; echo 'PKG_CXXFLAGS := ${PKG_CXXFLAGS} -Wall -Wextra -pedantic -Werror' > ~/.R/Makevars

after_success:
- Rscript -e 'covr::codecov()'






